
package javaClient.stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Chambre", targetNamespace = "http://appSOAP/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Chambre {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getType", targetNamespace = "http://appSOAP/", className = "javaClient.stub.GetType")
    @ResponseWrapper(localName = "getTypeResponse", targetNamespace = "http://appSOAP/", className = "javaClient.stub.GetTypeResponse")
    @Action(input = "http://appSOAP/Chambre/getTypeRequest", output = "http://appSOAP/Chambre/getTypeResponse")
    public String getType();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setPrix", targetNamespace = "http://appSOAP/", className = "javaClient.stub.SetPrix")
    @ResponseWrapper(localName = "setPrixResponse", targetNamespace = "http://appSOAP/", className = "javaClient.stub.SetPrixResponse")
    @Action(input = "http://appSOAP/Chambre/setPrixRequest", output = "http://appSOAP/Chambre/setPrixResponse")
    public void setPrix(
        @WebParam(name = "arg0", targetNamespace = "")
        float arg0);

    /**
     * 
     * @return
     *     returns float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPrix", targetNamespace = "http://appSOAP/", className = "javaClient.stub.GetPrix")
    @ResponseWrapper(localName = "getPrixResponse", targetNamespace = "http://appSOAP/", className = "javaClient.stub.GetPrixResponse")
    @Action(input = "http://appSOAP/Chambre/getPrixRequest", output = "http://appSOAP/Chambre/getPrixResponse")
    public float getPrix();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendType")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "SendType", targetNamespace = "http://appSOAP/", className = "javaClient.stub.SendType")
    @ResponseWrapper(localName = "SendTypeResponse", targetNamespace = "http://appSOAP/", className = "javaClient.stub.SendTypeResponse")
    @Action(input = "http://appSOAP/Chambre/SendTypeRequest", output = "http://appSOAP/Chambre/SendTypeResponse")
    public String sendType();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setType", targetNamespace = "http://appSOAP/", className = "javaClient.stub.SetType")
    @ResponseWrapper(localName = "setTypeResponse", targetNamespace = "http://appSOAP/", className = "javaClient.stub.SetTypeResponse")
    @Action(input = "http://appSOAP/Chambre/setTypeRequest", output = "http://appSOAP/Chambre/setTypeResponse")
    public void setType(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
